#Importing libraries:

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import r2_score, mean_squared_error

#Importing dataset

In [ ]:
dataset = pd.read_csv('/content/Data C.csv')

In [ ]:
dataset

Sample code number  Clump Thickness  ...  Mitoses  Class
0               1000025                5  ...        1      2
1               1002945                5  ...        1      2
2               1015425                3  ...        1      2
3               1016277                6  ...        1      2
4               1017023                4  ...        1      2
..                  ...              ...  ...      ...    ...
678              776715                3  ...        1      2
679              841769                2  ...        1      2
680              888820                5  ...        2      4
681              897471                4  ...        1      4
682              897471                4  ...        1      4

[683 rows x 11 columns]

#Spiltting of data

In [ ]:
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test,y_train,y_test = train_test_split(x, y, test_size=0.20)

In [ ]:
y_train

array([4, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       4, 4, 2, 2, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 2, 4, 2, 2, 4, 2, 2,
       2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 4, 2, 2, 4, 4, 4, 4, 2,
       2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 2, 4, 2, 4, 4, 2,
       4, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 4, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 2, 4, 2,
       4, 2, 2, 4, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2,
       2, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2,
       4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2,
       2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 4, 2,
       2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2,
       2, 2, 4, 2, 4, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2,

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train

array([[ 0.94577331,  0.04071913, -0.1021446 , ...,  1.45482839,
         0.33044488, -0.36092263],
       [-0.73738258, -0.65405096, -0.55928356, ..., -1.00695767,
        -0.62925141, -0.36092263],
       [-0.73738258, -0.65405096, -0.55928356, ..., -0.18636231,
        -0.30935265, -0.36092263],
       ...,
       [-0.73738258, -0.65405096, -0.55928356, ..., -0.18636231,
        -0.62925141, -0.36092263],
       [ 0.94577331,  0.73548921,  1.72641122, ...,  1.45482839,
         1.29014117,  0.74617712],
       [-0.73738258, -0.65405096, -0.55928356, ..., -0.18636231,
        -0.62925141, -0.36092263]])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
lcla = LogisticRegression()
kcla = KNeighborsClassifier(n_neighbors=3)
dcla = DecisionTreeClassifier()
rcla = RandomForestClassifier()

In [ ]:
lcla.fit(X_train,y_train)
kcla.fit(X_train, y_train)
dcla.fit(X_train, y_train)
rcla.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
lrpd=lcla.predict(X_test)
kpd = kcla.predict(X_test)
dtpd = dcla.predict(X_test)
rfpd = rcla.predict(X_test)

In [ ]:
log_acc = accuracy_score(y_test, lrpd)
k_acc = accuracy_score(y_test, kpd)
d_acc = accuracy_score(y_test, dtpd)
rf_acc = accuracy_score(y_test, rfpd)

In [ ]:
log_cm = confusion_matrix(y_test, lrpd)
k_cm = confusion_matrix(y_test, kpd)
d_cm = confusion_matrix(y_test, dtpd)
rf_cm = confusion_matrix(y_test, rfpd)

In [ ]:
svm_cla = SVC(kernel = 'poly')

In [ ]:
svm_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svm_poly_pd = svm_cla.predict(X_test)
svm_poly_acc = accuracy_score(y_test, svm_poly_pd)
svm_poly_cm = confusion_matrix(y_test,svm_poly_pd)

NameError: ignored

In [ ]:
svm_rbf_cla = SVC(kernel = 'rbf')

In [ ]:
svm_rbf_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svm_rbf_pd = svm_rbf_cla.predict(X_test)
svm_rbf_acc = accuracy_score(y_test, svm_rbf_pd)
svm_rbf_cm = confusion_matrix(y_test, svm_rbf_pd)

In [ ]:
svm_sig_cla = SVC(kernel = 'sigmoid')

In [ ]:
svm_sig_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svm_sig_pd = svm_sig_cla.predict(X_test)
svm_sig_acc = accuracy_score(y_test, svm_sig_pd)
svm_sig_cm = confusion_matrix(y_test, svm_sig_pd)

In [ ]:
log_cm

array([[54,  4],
       [13, 11]])

In [ ]:
log_acc

0.7926829268292683

In [ ]:
k_cm

array([[48, 10],
       [17,  7]])

In [ ]:
k_acc

0.6707317073170732

In [ ]:
d_cm

array([[43, 15],
       [16,  8]])

In [ ]:
d_acc

0.6219512195121951

In [ ]:
rf_cm

array([[56,  2],
       [15,  9]])

In [ ]:
rf_acc

0.7926829268292683

In [ ]:
svm_li_cm

array([[54,  4],
       [16,  8]])

In [ ]:
svm_li_acc

0.7560975609756098

In [ ]:
svm_rbf_cm

array([[58,  0],
       [18,  6]])

In [ ]:
svm_rbf_acc

0.7804878048780488

In [ ]:
svm_sig_cm

array([[57,  1],
       [20,  4]])

In [ ]:
svm_sig_acc

0.7439024390243902